/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WordlistAutocompletePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var WordlistSuggest = class extends import_obsidian.EditorSuggest {
  constructor(plugin) {
    super(plugin.app);
    this.wordData = new Map();
    this.plugin = plugin;
    this.loadWordlists();
  }
  shorthand(word) {
    if (!word) return word;
    const first = word[0];
    const rest = word.slice(1).replace(/[aeiouAEIOU]/g, '');
    return first + rest;
  }
  
  async loadWordlists() {
    this.wordData.clear();
    
    for (const fileConfig of this.plugin.settings.enabledFiles) {
      if (!fileConfig.enabled) continue;
      
      try {
        const file = this.plugin.app.vault.getAbstractFileByPath(fileConfig.path);
        if (file instanceof import_obsidian.TFile && file.extension === 'json') {
          const content = await this.plugin.app.vault.read(file);
          const jsonData = JSON.parse(content);
          
          for (const [word, metadata] of Object.entries(jsonData)) {
            const categoryOrder = fileConfig.categoryOrder[metadata.category] || 999;
            this.wordData.set(word.toLowerCase(), {
              word: word,
              domain: metadata.domain,
              category: metadata.category,
              frequency: metadata.frequency || 1,
              fileOrder: fileConfig.order,
              categoryOrder: categoryOrder
            });
          }
        }
      } catch (error) {
        console.error(`Failed to load wordlist ${fileConfig.path}:`, error);
      }
    }
  }
  onTrigger(cursor, editor) {
    const line = editor.getLine(cursor.line);
    const beforeCursor = line.substring(0, cursor.ch);
    const minLength = this.plugin.settings.minLetters;
    const match = beforeCursor.match(new RegExp(`\\b(\\w{${minLength},})$`));
    if (match) {
      return {
        start: { line: cursor.line, ch: cursor.ch - match[1].length },
        end: cursor,
        query: match[1]
      };
    }
    return null;
  }
  getSuggestions(context) {
    const query = context.query.toLowerCase();
    const suggestions = [];
    const shorthandQuery = this.shorthand(query);
    
    for (const [word, data] of this.wordData) {
      const matchType = this.getMatchType(word, query, shorthandQuery);
      if (matchType) {
        suggestions.push({
          word: data.word,
          domain: data.domain,
          category: data.category,
          frequency: data.frequency,
          fileOrder: data.fileOrder,
          categoryOrder: data.categoryOrder,
          match: matchType
        });
      }
    }
    
    return this.rankSuggestions(suggestions).slice(0, 10);
  }
  
  getMatchType(word, query, shorthandQuery) {
    if (word.startsWith(query)) return 'prefix';
    if (this.plugin.settings.enableShorthand && this.shorthand(word).toLowerCase().startsWith(shorthandQuery)) return 'shorthand';
    if (word.includes(query)) return 'contains';
    return null;
  }
  
  rankSuggestions(suggestions) {
    const globalOrder = this.plugin.settings.globalOrder;
    
    return suggestions.sort((a, b) => {
      // Primary: match type
      const matchOrder = { prefix: 0, shorthand: 1, contains: 2 };
      if (a.match !== b.match) {
        return matchOrder[a.match] - matchOrder[b.match];
      }
      
      // Secondary: global order
      if (globalOrder === 'file') {
        if (a.fileOrder !== b.fileOrder) return a.fileOrder - b.fileOrder;
      } else if (globalOrder === 'category') {
        if (a.categoryOrder !== b.categoryOrder) return a.categoryOrder - b.categoryOrder;
      } else if (globalOrder === 'frequency') {
        if (a.frequency !== b.frequency) return b.frequency - a.frequency;
      }
      
      // Tertiary: alphabetical
      return a.word.localeCompare(b.word);
    });
  }
  renderSuggestion(suggestion, el) {
    const container = el.createEl('div', { cls: 'wordlist-suggestion' });
    container.createEl('span', { text: suggestion.word, cls: 'word' });
    
    const meta = container.createEl('div', { cls: 'meta' });
    meta.createEl('span', { text: suggestion.domain, cls: 'domain' });
    meta.createEl('span', { text: suggestion.category, cls: 'category' });
  }
  selectSuggestion(suggestion, evt) {
    const { context } = this;
    if (context) {
      const editor = context.editor;
      let insertWord = suggestion.word;
      
      if (this.plugin.settings.preserveCase) {
        const query = context.query;
        if (query === query.toUpperCase()) {
          insertWord = suggestion.word.toUpperCase();
        } else if (query === query.toLowerCase()) {
          insertWord = suggestion.word.toLowerCase();
        } else if (query[0] === query[0].toUpperCase()) {
          insertWord = suggestion.word[0].toUpperCase() + suggestion.word.slice(1).toLowerCase();
        }
      }
      
      editor.replaceRange(insertWord + " ", context.start, context.end);
    }
  }
};
var DEFAULT_SETTINGS = {
  minLetters: 3,
  dictionaryFolder: '',
  enabledFiles: [],
  globalOrder: 'file',
  enableShorthand: true,
  preserveCase: false
};
var WordlistAutocompletePlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.suggestor = new WordlistSuggest(this);
    this.registerEditorSuggest(this.suggestor);
    this.addSettingTab(new WordlistSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  
  async reloadWordlists() {
    if (this.suggestor) {
      await this.suggestor.loadWordlists();
    }
  }
};



var CategoryOrderModal = class extends import_obsidian.Modal {
  constructor(app, categories, currentOrder, onSubmit) {
    super(app);
    this.categories = categories;
    this.currentOrder = currentOrder;
    this.onSubmit = onSubmit;
  }
  
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Set category order" });
    
    const categoryList = contentEl.createDiv({ cls: "category-list" });
    
    const sortedCategories = this.categories.sort((a, b) => {
      const orderA = this.currentOrder[a] || 999;
      const orderB = this.currentOrder[b] || 999;
      return orderA - orderB;
    });
    
    sortedCategories.forEach((category, index) => {
      const categoryDiv = categoryList.createDiv({ cls: "category-item" });
      const dragHandle = categoryDiv.createDiv({ cls: "drag-handle", text: "⋮⋮" });
      const nameDiv = categoryDiv.createDiv({ cls: "category-name", text: category });
      
      this.setupCategoryDragAndDrop(dragHandle, categoryDiv);
    });
    
    new import_obsidian.Setting(contentEl)
      .addButton(btn => btn.setButtonText("Save").setCta().onClick(() => {
        const newOrder = {};
        const categoryItems = categoryList.querySelectorAll('.category-item');
        categoryItems.forEach((item, index) => {
          const categoryName = item.querySelector('.category-name').textContent;
          newOrder[categoryName] = index;
        });
        this.onSubmit(newOrder);
        this.close();
      }))
      .addButton(btn => btn.setButtonText("Cancel").onClick(() => this.close()));
  }
  
  setupCategoryDragAndDrop(dragHandle, categoryDiv) {
    let isDragging = false;
    let startY = 0;
    
    dragHandle.addEventListener('mousedown', (e) => {
      isDragging = false;
      startY = e.clientY;
      
      const onMouseMove = (e) => {
        if (!isDragging && Math.abs(e.clientY - startY) > 5) {
          isDragging = true;
          categoryDiv.classList.add('dragging');
        }
        
        if (isDragging) {
          const afterElement = this.getCategoryDragAfterElement(categoryDiv.parentElement, e.clientY);
          if (afterElement == null) {
            categoryDiv.parentElement.appendChild(categoryDiv);
          } else {
            categoryDiv.parentElement.insertBefore(categoryDiv, afterElement);
          }
        }
      };
      
      const onMouseUp = () => {
        if (isDragging) {
          categoryDiv.classList.remove('dragging');
        }
        document.removeEventListener('mousemove', onMouseMove);
        document.removeEventListener('mouseup', onMouseUp);
      };
      
      document.addEventListener('mousemove', onMouseMove);
      document.addEventListener('mouseup', onMouseUp);
      e.preventDefault();
    });
  }
  
  getCategoryDragAfterElement(container, y) {
    const draggableElements = [...container.querySelectorAll('.category-item:not(.dragging)')];
    
    return draggableElements.reduce((closest, child) => {
      const box = child.getBoundingClientRect();
      const offset = y - box.top - box.height / 2;
      
      if (offset < 0 && offset > closest.offset) {
        return { offset: offset, element: child };
      } else {
        return closest;
      }
    }, { offset: Number.NEGATIVE_INFINITY }).element;
  }
  
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

var WordlistSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Wordlist Autocomplete Settings" });
    
    new import_obsidian.Setting(containerEl).setName("Minimum letters to trigger").setDesc("Number of letters needed before autocomplete appears").addSlider((slider) => slider.setLimits(1, 10, 1).setValue(this.plugin.settings.minLetters).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.minLetters = value;
      await this.plugin.saveSettings();
    }));
    
    new import_obsidian.Setting(containerEl).setName("Enable shorthand matching").setDesc("Allow typing 'orcl' to match 'Oracle'").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableShorthand).onChange(async (value) => {
      this.plugin.settings.enableShorthand = value;
      await this.plugin.saveSettings();
    }));
    
    new import_obsidian.Setting(containerEl).setName("Preserve case").setDesc("Match input case in suggestions").addToggle((toggle) => toggle.setValue(this.plugin.settings.preserveCase).onChange(async (value) => {
      this.plugin.settings.preserveCase = value;
      await this.plugin.saveSettings();
    }));
    
    new import_obsidian.Setting(containerEl).setName("Dictionary folder").setDesc("Folder containing JSON dictionary files").addDropdown((dropdown) => {
      const folders = this.getVaultFolders();
      dropdown.addOption("", "Select folder...");
      folders.forEach(folder => dropdown.addOption(folder, folder));
      dropdown.setValue(this.plugin.settings.dictionaryFolder).onChange(async (value) => {
        this.plugin.settings.dictionaryFolder = value;
        await this.plugin.saveSettings();
        if (value) {
          this.loadFilesFromFolder();
        }
        this.display();
      });
    });
    
    if (this.plugin.settings.dictionaryFolder) {
      containerEl.createEl("div", { text: `Current folder: ${this.plugin.settings.dictionaryFolder}`, cls: "setting-item-description" });
    }
    
    new import_obsidian.Setting(containerEl).setName("Global suggestion order").setDesc("Primary ordering method for suggestions").addDropdown((dropdown) => dropdown.addOption("file", "File order").addOption("category", "Category order").addOption("frequency", "Frequency").addOption("alphabetical", "Alphabetical").setValue(this.plugin.settings.globalOrder).onChange(async (value) => {
      this.plugin.settings.globalOrder = value;
      await this.plugin.saveSettings();
    }));
    
    this.displayFileSettings(containerEl);
  }
  
  displayFileSettings(containerEl) {
    if (!this.plugin.settings.dictionaryFolder) return;
    
    containerEl.createEl("h3", { text: "Dictionary Files" });
    
    const fileListDiv = containerEl.createDiv({ cls: "file-list" });
    
    this.plugin.settings.enabledFiles.forEach((fileConfig, index) => {
      const fileDiv = fileListDiv.createDiv({ cls: "file-config", attr: { "data-index": index } });
      
      const dragHandle = fileDiv.createDiv({ cls: "drag-handle", text: "⋮⋮" });
      
      const contentDiv = fileDiv.createDiv({ cls: "file-content" });
      
      new import_obsidian.Setting(contentDiv)
        .setName(fileConfig.path.split('/').pop())
        .addToggle(toggle => toggle.setValue(fileConfig.enabled).onChange(async (value) => {
          this.plugin.settings.enabledFiles[index].enabled = value;
          await this.plugin.saveSettings();
          await this.plugin.reloadWordlists();
        }))

        .addButton(btn => btn.setButtonText("Category order").onClick(async () => {
          const categories = await this.getCategoriesFromFile(fileConfig.path);
          const modal = new CategoryOrderModal(this.plugin.app, categories, fileConfig.categoryOrder, (newOrder) => {
            this.plugin.settings.enabledFiles[index].categoryOrder = newOrder;
            this.plugin.saveSettings();
          });
          modal.open();
        }));
      
      this.setupDragAndDrop(dragHandle, fileDiv, index);
    });
  }
  
  setupDragAndDrop(dragHandle, fileDiv, index) {
    let isDragging = false;
    let startY = 0;
    let startIndex = index;
    
    dragHandle.addEventListener('mousedown', (e) => {
      isDragging = false;
      startY = e.clientY;
      startIndex = Array.from(fileDiv.parentElement.children).indexOf(fileDiv);
      
      const onMouseMove = (e) => {
        if (!isDragging && Math.abs(e.clientY - startY) > 5) {
          isDragging = true;
          fileDiv.classList.add('dragging');
        }
        
        if (isDragging) {
          const afterElement = this.getDragAfterElement(fileDiv.parentElement, e.clientY);
          if (afterElement == null) {
            fileDiv.parentElement.appendChild(fileDiv);
          } else {
            fileDiv.parentElement.insertBefore(fileDiv, afterElement);
          }
        }
      };
      
      const onMouseUp = async () => {
        if (isDragging) {
          fileDiv.classList.remove('dragging');
          const newIndex = Array.from(fileDiv.parentElement.children).indexOf(fileDiv);
          if (startIndex !== newIndex) {
            await this.reorderFiles(startIndex, newIndex);
          }
        }
        document.removeEventListener('mousemove', onMouseMove);
        document.removeEventListener('mouseup', onMouseUp);
      };
      
      document.addEventListener('mousemove', onMouseMove);
      document.addEventListener('mouseup', onMouseUp);
      e.preventDefault();
    });
  }
  
  getDragAfterElement(container, y) {
    const draggableElements = [...container.querySelectorAll('.file-config:not(.dragging)')];
    
    return draggableElements.reduce((closest, child) => {
      const box = child.getBoundingClientRect();
      const offset = y - box.top - box.height / 2;
      
      if (offset < 0 && offset > closest.offset) {
        return { offset: offset, element: child };
      } else {
        return closest;
      }
    }, { offset: Number.NEGATIVE_INFINITY }).element;
  }
  
  async reorderFiles(fromIndex, toIndex) {
    const files = this.plugin.settings.enabledFiles;
    const [movedFile] = files.splice(fromIndex, 1);
    files.splice(toIndex, 0, movedFile);
    
    files.forEach((file, i) => {
      file.order = i;
    });
    
    await this.plugin.saveSettings();
    await this.plugin.reloadWordlists();
    this.display();
  }
  
  async loadFilesFromFolder() {
    const folderPath = this.plugin.settings.dictionaryFolder;
    const files = this.plugin.app.vault.getFiles().filter(file => 
      file.path.startsWith(folderPath) && file.extension === 'json'
    );
    
    this.plugin.settings.enabledFiles = files.map((file, index) => ({
      path: file.path,
      enabled: false,
      order: index,
      categoryOrder: {}
    }));
    
    // Sort by current order if exists
    this.plugin.settings.enabledFiles.sort((a, b) => a.order - b.order);
    
    await this.plugin.saveSettings();
  }
  
  getVaultFolders() {
    const folders = [];
    const allFiles = this.plugin.app.vault.getAllLoadedFiles();
    
    allFiles.forEach(file => {
      if (file instanceof import_obsidian.TFolder) {
        folders.push(file.path);
      }
    });
    
    return folders.sort();
  }
  
  async getCategoriesFromFile(filePath) {
    try {
      const file = this.plugin.app.vault.getAbstractFileByPath(filePath);
      if (file instanceof import_obsidian.TFile) {
        const content = await this.plugin.app.vault.read(file);
        const jsonData = JSON.parse(content);
        return [...new Set(Object.values(jsonData).map(item => item.category))];
      }
    } catch (error) {
      console.error(`Error reading categories from ${filePath}:`, error);
    }
    return [];
  }
};