/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WordlistAutocompletePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var WordlistSuggest = class extends import_obsidian.EditorSuggest {
  constructor(plugin) {
    super(plugin.app);
    this.words = [];
    this.plugin = plugin;
    this.loadWordlist();
  }
  async loadWordlist() {
    try {
      const file = this.plugin.app.vault.getAbstractFileByPath("mega_wordlist.txt");
      if (file instanceof import_obsidian.TFile) {
        const content = await this.plugin.app.vault.read(file);
        this.words = content.split(/\r?\n/).filter((word) => word.trim().length > 0);
      }
    } catch (error) {
      console.error("Failed to load wordlist:", error);
    }
  }
  onTrigger(cursor, editor) {
    const line = editor.getLine(cursor.line);
    const beforeCursor = line.substring(0, cursor.ch);
    const match = beforeCursor.match(/\b(\w{3,})$/);
    if (match) {
      return {
        start: { line: cursor.line, ch: cursor.ch - match[1].length },
        end: cursor,
        query: match[1]
      };
    }
    return null;
  }
  getSuggestions(context) {
    const query = context.query.toLowerCase();
    return this.words.filter((word) => word.toLowerCase().startsWith(query)).slice(0, 10).map((word) => ({ word }));
  }
  renderSuggestion(suggestion, el) {
    el.createEl("div", { text: suggestion.word });
  }
  selectSuggestion(suggestion, evt) {
    const { context } = this;
    if (context) {
      const editor = context.editor;
      editor.replaceRange(suggestion.word, context.start, context.end);
    }
  }
};
var WordlistAutocompletePlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.suggestor = new WordlistSuggest(this);
    this.registerEditorSuggest(this.suggestor);
  }
  onunload() {
  }
};
